package dev.razil.lilhub.ui.home

import androidx.lifecycle.ViewModel
import dev.razil.lilhub.data.Repository
import javax.inject.Inject

/**
 * [ViewModel] that provides and manages data for [HomeFragment] and for handling events generated by user actions.
 *
 * @param repo An instance of [Repository]
 */
class HomeViewModel @Inject constructor(private val repo: Repository) : ViewModel()
